name: Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          python3 publish.py
#          twine upload -u __token__ -p ${{ secrets.PYPI_UPLOAD_TWINE_TOKEN }} dist/*